# Generated by Django 4.2.1 on 2023-08-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('手机号', models.CharField(max_length=11, verbose_name='手机号')),
                ('应用商', models.CharField(max_length=10, verbose_name='应用商')),
                ('所选app', models.CharField(max_length=10, verbose_name='所选app')),
                ('操作', models.CharField(max_length=5, verbose_name='操作')),
                ('时间戳', models.CharField(max_length=25, verbose_name='时间戳')),
            ],
        ),
        migrations.CreateModel(
            name='UsrData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('哈希索引', models.CharField(max_length=45, verbose_name='哈希索引')),
                ('手机号', models.CharField(max_length=11, verbose_name='手机号')),
                ('应用商', models.CharField(max_length=10, verbose_name='应用商')),
                ('所选app', models.CharField(max_length=10, verbose_name='所选app')),
                ('操作', models.CharField(max_length=5, verbose_name='操作')),
                ('当前状态', models.CharField(max_length=10, verbose_name='当前状态')),
                ('时间戳', models.CharField(max_length=25, verbose_name='时间戳')),
            ],
        ),
    ]
