# Generated by Django 4.2.1 on 2023-08-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('handle', '0002_rename_所选app_history_app_rename_操作_history_op_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='Op',
            field=models.CharField(max_length=10, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='usrdata',
            name='Op',
            field=models.CharField(max_length=10, verbose_name='操作'),
        ),
    ]
